name: Build & Push Docker -> GHCR

on:
  push:
    branches: [main]
    paths:
      - 'docker/Dockerfile'                 # trigger only if this file changes
      - '.github/workflows/docker-ghcr.yml' # or if the workflow changes
  pull_request:
    paths:
      - 'docker/Dockerfile'
      - '.github/workflows/docker-ghcr.yml'
  workflow_dispatch:                        # optional manual run

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GCHR_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: ./docker            # directory that contains the Dockerfile
          file: ./docker/Dockerfile    # explicit path to the Dockerfile
          push: true
          tags: |
            ghcr.io/phylliida/bailstudy:latest
            ghcr.io/phylliida/bailstudy:${{ github.sha }}